name: Release

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: "Install bun"
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest

        - name: "Install dependencies"
          run: bun install --frozen-lockfile

        - name: Checks
          run: bun run checks
        
        - name: Test
          run: bun run test:single

        - name: Build
          run: bun run build

        - name: "Publish"
          run: bun publish --access public
          env:
            NPM_CONFIG_TOKEN: ${{secrets.NPM_CONFIG_TOKEN}}